config/routes.rb
Rails.application.routes.draw do
  # resources :comments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "tweets#index"
  resources :tweets do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }
  
  belongs_to :user
  belongs_to :tweet, counter_cache: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\w+@\w+\.\w{1,3}/i.freeze
  
  validates :username, presence: true, uniqueness: true, length: { maximum: 16 }
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments
  def index
    @comments = Comment.where(tweet_id: params[:tweet_id]).order(updated_at: :desc)
    @comment = @tweet.comments.new
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.new
  end

  # GET /comments/1/edit
  def edit
    @tweet = Tweet.find(params[:tweet_id])
    # @comment = @tweet.comments.new
  end

  # POST /comments
  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.new(comment_params)
    user = current_user
    @comment.user = user

    if @comment.save
      redirect_to @tweet, notice: "Comment was successfully created."
    else
      render @tweet, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: "Comment was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets
  def index
    @tweets = Tweet.order(updated_at: :desc)
    @tweet = Tweet.new
    @tweet.user = current_user
  end

  # GET /tweets/1
  def show
    @comment = Comment.new
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    @tweets = Tweet.order(updated_at: :desc)

    if @tweet.save
      redirect_to :tweets, notice: "Tweet was successfully created."
    else
      render "tweets/index", status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: "Tweet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: "Tweet was successfully destroyed."
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(record, attribute)
    errors = record.errors.full_messages_for(attribute).map do |message|
      content_tag(:span, message, class: "input__error-message")
    end

    safe_join(errors)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def capitalize_first_letter(word)
    word.split.map { |w| w.capitalize }.join(" ")
  end
end

app/views/comments/_comment.html.erb
<% user = @tweet.user %>

<div id="<%= dom_id comment %>">
  <article class="comment">
    <div class="comment__image-content">
      <% if user.avatar.attached? %>
        <%= image_tag avatar, class: "comment__image" %>
      <% else %>
        <%= image_tag "icons/user.svg", class: "comment__image" %>
      <% end %>
    </div>
    <div class="comment__content">
      <div class="comment__header">
        <div class="comment__data">
          <%= content_tag :span, capitalize_first_letter(comment.user.name), class: "heading--r" %>
          <span class="comment__date content-r"><%= "@#{comment.user.username}" %></span>
          <span class="comment__date content-sm">
            <%= "updated" if comment.created_at != comment.updated_at %>
            <%= distance_of_time_in_words_to_now(comment.updated_at) %>
          </span>
        </div>
      </div>
      <p class="content-r">
        <%= comment.body %>
      </p>
      <div class="comment__footer">
        <% if comment.user == current_user %>
          <div class="comment__footer-comments">
            <%=link_to image_tag("icons/edit.svg"), 
                        edit_tweet_comment_path(comment)%>
            <%=button_to image_tag("icons/trash.svg"), 
                          "tweet_comment_path", 
                          method: :delete, "data-turbo": "false",
                          class: "action-icon"%>
          </div>
        <% end %>
      </div>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<% user = @tweet.user %>

<%= form_with model: [ @tweet, @tweet.comments.build ] do |form| %>
  <article class="comment mb-4">
    <div class="comment__image-content">
      <% if user.avatar.attached? %>
        <%= image_tag avatar, class: "comment__image" %>
      <% else %>
        <%= image_tag "icons/user.svg", class: "comment__image" %>
      <% end %>
    </div>
    <div class="comment__content">
      <div class="comment__area">
        <%= form.text_area :body, placeholder: "Remember to thing before write...", class: "comment__area" %>
      </div>

      <div class="comment__submit">
        <%= form.submit "comment", class: "button button--primary button--sm"%>
      </div>
    </div>
  </article>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", "tweet_comment_path" %> |
  <%= link_to "Back to comments", @tweet %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_tweet_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableIndividual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="container navbar">
        <%if user_signed_in?%>
          <%=link_to "Edit Profile", "#", class: "content-r"%>
          <%=button_to "Log Out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class: "button button--r button--ghost"%>
        <%else%>
          <%=link_to "Sign in", new_user_session_path%>
        <%end%>
      </div>
    </header>

    
    <main class="section">
      <section class="container">
        <p style="color: green"><%= notice %></p>
        <p style="color: red"><%= alert %></p>
        <%= yield %>
      </section>
    </main>
  </body>
</html>

app/views/tweets/_form.html.erb
<% user = tweet.user %>
<%= form_with(model: tweet) do |form| %>
  <article class="tweet mb-4">
    <div class="tweet__image-content">
      <% if user.avatar.attached? %>
        <%= image_tag avatar, class: "tweet__image" %>
      <% else %>
        <%= image_tag "icons/user.svg", class: "tweet__image" %>
      <% end %>
    </div>
    <div class="tweet__content">
      <div class="tweet__area">
        <%= form.text_area :body, placeholder: "Remember to thing before write...", class: "tweet__area" %>
      </div>
      <%=errors_for(tweet, :body)%>
      <div class="tweet__submit">
        <%= form.submit "Tweet", class: "button button--primary button--sm"%>
      </div>
    </div>
  </article>
<% end %>

app/views/tweets/_tweet.html.erb
<% user = tweet.user %>
<div id="<%= dom_id tweet %>">
  <article class="tweet">
    <div class="tweet__image-content">
      <% if user.avatar.attached? %>
        <%= image_tag avatar, class: "tweet__image" %>
      <% else %>
        <%= image_tag "icons/user.svg", class: "tweet__image" %>
      <% end %>
    </div>
    <div class="tweet__content">
      <div class="tweet__header">
        <div class="tweet__data">
          <%= content_tag :span, capitalize_first_letter(user.name), class: "heading--r" %>
          <span class="tweet__date content-r"><%= "@#{user.username}" %></span>
          <span class="tweet__date content-sm">
            <%= "updated" if tweet.created_at != tweet.updated_at %>
            <%= distance_of_time_in_words_to_now(tweet.updated_at) %>
          </span>
        </div>
      </div>
      <p class="content-r">
        <%= tweet.body %>
      </p>
      <div class="tweet__footer">
        <div class="tweet__footer-comments">
          <%= image_tag "icons/replies.svg" %>
          <%= link_to tweet.comments_count, tweet, class: "content-sm secondary-text" %>
        </div>
        <% if user == current_user %>
          <div class="tweet__footer-comments">
            <%=link_to image_tag("icons/edit.svg"), 
                        edit_tweet_path(tweet)%>
            <%=button_to image_tag("icons/trash.svg"), 
                          tweet, 
                          method: :delete, "data-turbo": "false",
                          class: "action-icon"%>
          </div>
        <% end %>
      </div>
    </div>
  </article>
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="tweet-header mb-1"><h1 class="heading--lg">Home</h1></div>
<%if user_signed_in?%>
  <%= render "form", tweet: @tweet %>
<%end%>
<div class="mb-4" id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="mb-4">
  <%= render @tweet %>
</div>

<%if user_signed_in?%>
  <%= render 'comments/form' %>
<%end%>

<% @tweet = Tweet.find(params[:id]) %>

<%= render @tweet.comments.order(updated_at: :desc) %>